version: "3.8"

services:
  server:
    image: cluejws/soundie
    container_name: server-container
    networks:
      - my-network
    ports:
      - "8080:8080"
    volumes:
      - ./src/main/resources/application.yml:/app/application.yml
    env_file:
      - .env.prod
    environment:
      SPRING_CONFIG_LOCATION: /app/application.yml
      SPRING_PROFILES_ACTIVE: prod  # 활성 프로파일
      SPRING_PROFILE: prod  # 이 줄을 추가
    depends_on:
      - db
      - redis
      - kafka

  db:
    image: mysql:latest
    container_name: db-container
    networks:
      - my-network
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}    # .env.prod에서 가져오기
      MYSQL_DATABASE: ${MYSQL_DATABASE}         # .env.prod에서 가져오기

  redis:
    image: redis:latest
    container_name: redis-container
    networks:
      - my-network
    ports:
      - "6381:6380"
    command: ["redis-server", "--port", "6380"]

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper-container
    networks:
      - my-network
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: kafka-container
    networks:
      - my-network
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://${KAFKA_DOMAIN}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

networks:
  my-network:
    external: true
