# spring
spring:
  config:
    activate:
      on-profile: local
    import: application-secret.yaml

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa

  h2:
    console:
      enabled: true
      path: /h2-console

  schedule:
    fixed-delay: 1000
    initial-delay: 1000

  # kafka
  kafka:
    # Kafka 클러스터에 대한 주소
    bootstrap-servers: localhost:9092

    # Kafka 토픽
    template:
      default-topic: chatroom

    # Kafka 컨슈머에 대한 설정
    consumer:
      # 컨슈머 그룹의 고유 식별자인 그룹 ID를 설정
      group-id: foo

      # 마지막 커밋 기록이 없을 경우, 가장 예전(낮은 번호 오프셋) 레코드부터 처리
      auto-offset-reset: earliest

  # redis
  redis:
    db:
      host: localhost
      port: 6379
    cache:
      host: localhost
      port: 6380

# mybatis
mybatis:
  mapper-locations: classpath*:mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

# cloud
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: ${S3_BUCKET_NAME}
      expire-in: ${S3_EXPIRE_IN_TIME}
