# spring
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa

  h2:
    console:
      enabled: true
      path: /h2-console

# mybatis
mybatis:
  mapper-locations: classpath*:mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
